apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: martinschurig-com
  namespace: default
  labels:
    app: martinschurig-com
    component: ingress
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: test.martinschurig.com
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress
          servicePort: 80
      - path: /great-things/
        backend:
          serviceName: martinschurig-com
          servicePort: 80
  tls:
  - hosts:
    - test.martinschurig.com
    secretName: martinschurig-com-tls
